### ISSUE TITLE
无权限调用智能体

### ISSUE THREAD

**Issue by dqzboy** [LLM-Red-Team/zhipuai-agent-to-openai#2]
如题，提示没有权限调用智能体，使用glm-free-api可以
![image](https://github.com/LLM-Red-Team/zhipuai-agent-to-openai/assets/42825450/ca54bb66-fa19-4f47-bdf4-cbbe4cc55ccc)
![image](https://github.com/LLM-Red-Team/zhipuai-agent-to-openai/assets/42825450/f434ec46-8634-4c59-a957-b51b802f47dc)

**Comment by Vinlic** [comment]
官方智能体API只允许调用由自己创建的智能体。
